### ISSUE TITLE
[BUG] #22 and #23 still happen on Linux

### ISSUE THREAD

**Issue by chrissxYT** [Amplissimus/Amplissimus#25]
**Describe the bug**
#22 and #23 still happen on Linux, and maybe Windows (can't test right now).

**Versions (please complete the following information):**
 - OS/Browser version: master
 - Version: 1.3.0

**Comment by Luddifee** [comment]
Should have been fixed in 1f105cb.

**Comment by chrissxYT** [comment]
this was mitigated for the first_login screen, the rest of the issues remain

**Comment by chrissxYT** [comment]
i just tested, it was fixed lol
